--CREATE DATABASE [VENDAS SUCOS];

--CREATE DATABASE [VENDAS SUCOS 2]
--ON(
--NAME = 'VENDAS_SUCOS_2_DAT',		-- NOME DO ARQUIVO
--FILENAME = 'C:\temp\VENDAS_SUCOS_2.MDF',		--CAMINHO DO ARQUIVO
--SIZE = 10MB,		-- O QUANTO O BANCO VAI CRESCER
--MAXSIZE = 50MB,			--TAMANHO MÁXIMO DO BANCO
--FILEGROWTH=5MB			--O BANCO VAI SUBIR DE 5 EM 5MB
--)
--LOG ON(
--NAME = 'VENDAS_SUCOS_2_LOG',		-- NOME DO ARQUIVO
--FILENAME = 'C:\temp\VENDAS_SUCOS_2.LDF',		--CAMINHO DO ARQUIVO
--SIZE = 10MB,		-- O QUANTO O BANCO VAI CRESCER
--MAXSIZE = 50MB,			--TAMANHO MÁXIMO DO BANCO
--FILEGROWTH=5MB			--O BANCO VAI SUBIR DE 5 EM 5MB
--);

--DROP DATABASE [VENDAS SUCOS 2]

--CREATE TABLE PRODUTOS
--(
--CODIGO VARCHAR(10) NOT NULL,
--DESCRITOR VARCHAR(100) NULL,
--SABOR VARCHAR(50) NULL,
--TAMANHO VARCHAR(50) NULL,
--EMBALAGEM VARCHAR(50) NULL,
--PRECO_LISTA FLOAT NULL,
--PRIMARY KEY (CODIGO)
--);

--CREATE TABLE VENDEDORES
--(
--MATRICULA VARCHAR(5) NOT NULL,
--NOME VARCHAR(100) NULL,
--BAIRRO VARCHAR(50) NULL,
--COMISSAO FLOAT NULL,
--DATA_ADMISSAO DATE NULL,
--FERIAS BIT NULL,
--PRIMARY KEY (MATRICULA)
--);

--CREATE TABLE CLIENTE
--(
--CPF VARCHAR(11) NOT NULL,
--NOME VARCHAR(100) NULL,
--ENDERECO VARCHAR(150) NULL,
--BAIRRO VARCHAR(50) NULL,
--CIDADE VARCHAR(50) NULL,
--ESTADO VARCHAR(50) NULL,
--CEP VARCHAR(8) NULL,
--DATA_NASCIMENTO DATE NULL,
--IDADE INT NULL,
--GENERO VARCHAR(1) NULL,
--LIMITE_CREDITO FLOAT NULL,
--PRIMEIRA_COMPRA BIT NULL,
--PRIMARY KEY (CPF)
--);

--CREATE TABLE TABELA_DE_VENDAS
--(
--NUMERO VARCHAR(5) NOT NULL,
--DATA_VENDA DATE NULL,
--CPF VARCHAR(11) NOT NULL,
--MATRICULA VARCHAR(11) NOT NULL,
--IMPOSTO FLOAT NULL,
--PRIMARY KEY (NUMERO)
--);

--ALTER TABLE TABELA_DE_VENDAS
--ADD CONSTRAINT FK_CLIENTES
--FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF);

--ALTER TABLE TABELA_DE_VENDAS
--ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL;

--ALTER TABLE TABELA_DE_VENDAS
--ADD CONSTRAINT FK_VENDEDORES
--FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

--CREATE TABLE TABELA_DE_ITENS_VENDIDOS
--(
--NUMERO VARCHAR(5) NOT NULL,
--CODIGO VARCHAR(10) NOT NULL,
--QUANTIDADE INT NULL,
--PRECO FLOAT NOT NULL,
--PRIMARY KEY (NUMERO,CODIGO)
--);

--ALTER TABLE TABELA_DE_ITENS_VENDIDOS
--ADD CONSTRAINT FK_TABELA_DE_VENDAS
--FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

--ALTER TABLE TABELA_DE_ITENS_VENDIDOS
--ADD CONSTRAINT FK_PRODUTOS
--FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);

--ALTER TABLE CLIENTE
--ADD VOLUME_COMPRA FLOAT NULL;

--exec sp_rename 'CLIENTE', 'CLIENTES';

--ALTER TABLE TABELA_DE_ITENS_VENDIDOS
--ALTER COLUMN QUANTIDADE FLOAT NULL;

--ALTER TABLE TABELA_DE_ITENS_VENDIDOS
--ALTER COLUMN PRECO FLOAT NULL;

--INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
--VALUES ('1040107','Light - 350 ml - Melância', 'Melância', '350 ml', 'Lata', 4.56)

--SELECT * FROM PRODUTOS

--INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
--VALUES ('1040108','Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00)

--INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
--VALUES ('1040109','Light - 350 ml - Açai', 'Açai', '350 ml', 'Lata', 5.60)

--INSERT INTO PRODUTOS 
--VALUES ('1040110','Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 3.50)

--INSERT INTO PRODUTOS 
--VALUES 
--('1040111','Light - 350 ml - Manga', 'Manga', '350 ml', 'Lata', 3.20),
--('1040112','Light - 350 ml - Maça', 'Maça', '350 ml', 'Lata', 4.20);

--INSERT INTO CLIENTES 
--(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,
--GENERO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)VALUES
--('19290992743','Érica Carvalho','R. Iriquitia','Jardins','São Paulo','SP',
--'80012212','1990-09-01',27,'F',170000,24500,0),
--('1471156710','Fernando Cavalcante','R. Dois de Fevereiro','Água Santa','Rio de Janeiro','RJ',
--'22000000','2000-02-12',18,'M',100000,20000,1),
--('2600586709','César Teixeira','Rua Conde de Bonfim','Tijuca','Rio de Janeiro','RJ',
--'22020001','2000-03-12',18,'M',120000,22000,0)

--SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

--SELECT * FROM PRODUTOS

--SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR,
--TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
--FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

--INSERT INTO PRODUTOS SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR,
--TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
--FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

--INSERT INTO PRODUTOS SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR,
--TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
--FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
--WHERE CODIGO_DO_PRODUTO <> '1040107';

--INSERT INTO CLIENTES
--SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
--IDADE, GENERO, LIMITE_DE_CREDITO AS LIMITE_CREDITO,PRIMEIRA_COMPRA, VOLUME_DE_COMPRA AS VOLUME_COMPRA
--FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
--WHERE CPF NOT IN ( '1471156710','19290992743','2600586709');

--SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
--SELECT * FROM [VENDAS SUCOS].DBO.CLIENTES

------- COMANDO INSERT CRIADO PELO SQL MANEGEMENT STUDIO:
--USE [VENDAS SUCOS]
--GO

--INSERT INTO [dbo].[PRODUTOS]
--           ([CODIGO]
--           ,[DESCRITOR]
--           ,[SABOR]
--           ,[TAMANHO]
--           ,[EMBALAGEM]
--           ,[PRECO_LISTA])
--     VALUES
--           ('1040113'
--           ,'Light - 350ml - Limão'
--           ,'Limão'
--           ,'350ml'
--           ,'Lata'
--           ,3.25)
--GO

--SELECT * FROM [VENDAS SUCOS]..TABELA_DE_VENDAS

--SELECT * FROM PRODUTOS;

--UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107';

--SELECT * FROM PRODUTOS WHERE SABOR = 'Manga';

--UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'Manga';

--SELECT DESCRITOR, REPLACE(DESCRITOR, '350 ml', '550 ml') FROM PRODUTOS WHERE TAMANHO = '350 ml'

--UPDATE PRODUTOS SET DESCRITOR = REPLACE(DESCRITOR, '350 ml', '550 ml'),
--TAMANHO = '550 ml' WHERE TAMANHO = '350 ml'

--SELECT DESCRITOR, TAMANHO, EMBALAGEM FROM PRODUTOS WHERE TAMANHO = '550 ml'

--SELECT * FROM CLIENTES WHERE CPF ='19290992743'

--UPDATE CLIENTES SET ENDERECO = 'R. Jorge Emilio 23',
--BAIRRO = 'Santo Amaro', CEP = '8833223'
--WHERE CPF ='19290992743'

--SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'

--UPDATE CLIENTES SET VOLUME_COMPRA = VOLUME_COMPRA * 1.2 WHERE ESTADO = 'RJ'

--SELECT * FROM PRODUTOS ORDER BY CODIGO;
--SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS ORDER BY CODIGO_DO_PRODUTO;

--UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

--SELECT
--A.CODIGO AS CODIGO_MINHA_TABELA,
--A.PRECO_LISTA AS PRECO_MINHA_TABELA,
--B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO,
--B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
--FROM PRODUTOS A
--INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
--ON A.CODIGO = B.CODIGO_DO_PRODUTO;


--UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA
--FROM PRODUTOS A
--INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
--ON A.CODIGO = B.CODIGO_DO_PRODUTO;

--UPDATE A SET VOLUME_COMPRA = VOLUME_COMPRA * 1.30
--FROM [dbo].[CLIENTES] A
--INNER JOIN [dbo].[VENDEDORES] B
--ON A.[BAIRRO] = B.[BAIRRO]

--SELECT A.CPF FROM [dbo].[CLIENTES] A
--INNER JOIN [dbo].[VENDEDORES] B
--ON A.[BAIRRO] = B.[BAIRRO]


--UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

--SELECT
--A.CODIGO AS CODIGO_MINHA_TABELA,
--A.PRECO_LISTA AS PRECO_MINHA_TABELA,
--B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO,
--B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
--FROM PRODUTOS A
--INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
--ON A.CODIGO = B.CODIGO_DO_PRODUTO;

--MERGE INTO PRODUTOS A
--USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
--ON A.CODIGO = B.CODIGO_DO_PRODUTO
--WHEN MATCHED THEN
--UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;


--SELECT A.CPF FROM [dbo].[CLIENTES] A
--INNER JOIN [dbo].[VENDEDORES] B
--ON A.[BAIRRO] = B.[BAIRRO]

--MERGE INTO [dbo].[CLIENTES] A
--USING [dbo].[VENDEDORES] B
--ON A.[BAIRRO] = B.[BAIRRO]
--WHEN MATCHED THEN
--UPDATE SET VOLUME_COMPRA = VOLUME_COMPRA * 1.30;

--INSERT INTO PRODUTOS 
--    (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
--VALUES 
--    ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50),
--    ('1001000','Sabor dos Alpes 700 ml - Melão','Melão','700 ml','Garrafa',7.50),
--    ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50),
--    ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50),
--    ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50),
--    ('1001005','Sabor dos Alpes 700 ml - Açai','Açai','700 ml','Garrafa',7.50),
--    ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50),
--    ('1001007','Sabor dos Alpes 1 Litro - Melão','Melão','1 Litro','Garrafa',7.50),
--    ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50),
--    ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50),
--    ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50),
--    ('1001011','Sabor dos Alpes 1 Litro - Açai','Açai','1 Litro','Garrafa',7.50);

--SELECT * FROM [PRODUTOS] WHERE SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes'
--AND TAMANHO = '1 Litro';

--DELETE FROM PRODUTOS WHERE CODIGO = '1001000'

--DELETE FROM PRODUTOS WHERE SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes'
--AND TAMANHO = '1 Litro';

--SELECT COUNT(*) FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;
--SELECT COUNT(*) FROM PRODUTOS;

--SELECT * FROM PRODUTOS
--WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS)

--DELETE FROM PRODUTOS
--WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS);

--SELECT TOP 1 * FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
--SELECT TOP 1 * FROM SUCOS_FRUTAS.DBO.NOTAS_FISCAIS

--SELECT A.NUMERO
--FROM SUCOS_FRUTAS.DBO.NOTAS_FISCAIS A
--INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES B
--ON A.[CPF] = B.[CPF] 
--WHERE B.[IDADE] < 18

--DELETE FROM SUCOS_FRUTAS.DBO.NOTAS_FISCAIS 
--WHERE NUMERO NOT IN (
--	SELECT A.NUMERO
--	FROM SUCOS_FRUTAS.DBO.NOTAS_FISCAIS A
--	INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES B
--	ON A.[CPF] = B.[CPF] 
--	WHERE B.[IDADE] < 18
--)

--DELETE A FROM SUCOS_FRUTAS.DBO.NOTAS_FISCAIS A
--INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES B
--ON A.[CPF] = B.[CPF] 
--	WHERE B.[IDADE] < 18;
----------------
--USE [VENDAS SUCOS]
--GO

--/****** Object:  Table [dbo].[PRODUTOS]    Script Date: 06/07/2024 06:48:25 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE TABLE [dbo].[PRODUTOS_2](
--	[CODIGO] [varchar](10) NOT NULL,
--	[DESCRITOR] [varchar](100) NULL,
--	[SABOR] [varchar](50) NULL,
--	[TAMANHO] [varchar](50) NULL,
--	[EMBALAGEM] [varchar](50) NULL,
--	[PRECO_LISTA] [float] NULL,
--PRIMARY KEY CLUSTERED 
--(
--	[CODIGO] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--) ON [PRIMARY]
--GO
----------------------------
--INSERT INTO PRODUTOS_2 SELECT * FROM PRODUTOS

--SELECT * FROM PRODUTOS
--SELECT * FROM PRODUTOS_2

--DELETE FROM PRODUTOS_2

--SELECT * FROM VENDEDORES

--BEGIN TRANSACTION

--SELECT * FROM VENDEDORES

--UPDATE VENDEDORES
--SET COMISSAO = COMISSAO * 1.1

--SELECT * FROM VENDEDORES

--COMMIT

--SELECT * FROM VENDEDORES

--BEGIN TRANSACTION

--INSERT INTO VENDEDORES
--VALUES ('239','Maria Joana','Copacabana',
--0.2,'2015-01-01',1);

--SELECT * FROM VENDEDORES

--ROLLBACK

--SELECT * FROM VENDEDORES

--CREATE TABLE TAB_IDENTITY
--(
--	ID INT IDENTITY(1,1) NOT NULL,
--	DESCRITOR VARCHAR(20) NULL
--);

--SELECT * FROM TAB_IDENTITY

--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X');
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y');
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z');
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE W');
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A');

--DELETE FROM TAB_IDENTITY WHERE ID = 1
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE B');
--DELETE FROM TAB_IDENTITY WHERE ID = 6
--INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE C');

--CREATE TABLE TAB_IDENTITY2
--(
--	ID INT IDENTITY(100,5) NOT NULL,
--	DESCRITOR VARCHAR(20) NULL
--);

--SELECT * FROM TAB_IDENTITY2

--INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE X');
--INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE Y');

--INSERT INTO TAB_IDENTITY2 (ID, DESCRITOR) VALUES (255, 'CLIENTE Z');

--CREATE TABLE TB_PADRAO
--(
--	ID INT IDENTITY(1,1) NOT NULL,
--	DESCRITOR VARCHAR(20) NULL,
--	ENDERECO VARCHAR(20) NULL,
--	CIDADE VARCHAR(20) DEFAULT 'Rio de Janeiro',
--	DATA_CRIACAO DATE DEFAULT GETDATE()
--);

--INSERT INTO TB_PADRAO (DESCRITOR,ENDERECO,CIDADE,DATA_CRIACAO)
--VALUES ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2018-04-30');

--SELECT * FROM TB_PADRAO

--INSERT INTO TB_PADRAO (DESCRITOR) VALUES ('CLIENTE Y');

--CREATE TABLE TAB_FATURAMENTO 
--(
--	DATA_VENDA DATE NULL,
--	TOTAL_VENDA FLOAT
--);

--SELECT
--TV.DATA_VENDA,
--SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--FROM TABELA_DE_VENDAS TV
--INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--ON TV.NUMERO = TIV.NUMERO
--GROUP BY 
--TV.DATA_VENDA

--SELECT * FROM CLIENTES
--SELECT * FROM PRODUTOS

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0100','2018-05-15','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0100', '1000889', 100, 10);

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0101','2018-05-15','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0101', '1000889', 100, 10);

--INSERT INTO TAB_FATURAMENTO
--SELECT
--TV.DATA_VENDA,
--SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--FROM TABELA_DE_VENDAS TV
--INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--ON TV.NUMERO = TIV.NUMERO
--GROUP BY 
--TV.DATA_VENDA

--SELECT * FROM TAB_FATURAMENTO

--INSERT INTO TAB_FATURAMENTO
--SELECT
--TV.DATA_VENDA,
--SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--FROM TABELA_DE_VENDAS TV
--INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--ON TV.NUMERO = TIV.NUMERO
--GROUP BY 
--TV.DATA_VENDA

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0102','2018-05-15','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0102', '1000889', 100, 10);

-----------------
--SELECT * FROM TAB_FATURAMENTO;

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0103','2018-05-15','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0103', '1000889', 100, 10);

--DELETE FROM TAB_FATURAMENTO;
--INSERT INTO TAB_FATURAMENTO
--SELECT
--TV.DATA_VENDA,
--SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--FROM TABELA_DE_VENDAS TV
--INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--ON TV.NUMERO = TIV.NUMERO
--GROUP BY 
--TV.DATA_VENDA;
--SELECT * FROM TAB_FATURAMENTO;

-----------------
--SELECT * FROM TAB_FATURAMENTO;

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0104','2018-05-16','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0104', '1000889', 100, 10);

--DELETE FROM TAB_FATURAMENTO;
--INSERT INTO TAB_FATURAMENTO
--SELECT
--TV.DATA_VENDA,
--SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--FROM TABELA_DE_VENDAS TV
--INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--ON TV.NUMERO = TIV.NUMERO
--GROUP BY 
--TV.DATA_VENDA;
--SELECT * FROM TAB_FATURAMENTO;

-----------------
--CREATE TRIGGER TG_ITENS_VENDIDOS
--ON [DBO].[TABELA_DE_ITENS_VENDIDOS]
--AFTER INSERT, UPDATE, DELETE
--AS 
--BEGIN
--	DELETE FROM TAB_FATURAMENTO;
--	INSERT INTO TAB_FATURAMENTO
--	SELECT
--	TV.DATA_VENDA,
--	SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
--	FROM TABELA_DE_VENDAS TV
--	INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
--	ON TV.NUMERO = TIV.NUMERO
--	GROUP BY 
--	TV.DATA_VENDA;
--END;
-------------------

--SELECT * FROM TAB_FATURAMENTO;

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0105','2018-05-16','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0105', '1000889', 150, 10);

--SELECT * FROM TAB_FATURAMENTO;

--INSERT INTO TABELA_DE_VENDAS
--VALUES ('0106','2018-05-16','1471156710','235',0.18);
--INSERT INTO TABELA_DE_ITENS_VENDIDOS
--VALUES ('0106', '1000889', 150, 10);

--SELECT * FROM TAB_FATURAMENTO;

--UPDATE TABELA_DE_ITENS_VENDIDOS SET QUANTIDADE = 200 WHERE NUMERO = '0106'

--SELECT * FROM TAB_FATURAMENTO;

--DELETE  FROM TABELA_DE_ITENS_VENDIDOS WHERE NUMERO = '0106'

--SELECT * FROM TAB_FATURAMENTO;

--SELECT * FROM CLIENTES

--SELECT [CPF], [NOME], [IDADE], [DATA_NASCIMENTO], 
--    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) AS IDADE_ATUAL
--FROM CLIENTES

--CREATE TRIGGER TG_CLIENTES_IDADE
--ON [DBO].[CLIENTES]
--AFTER INSERT, UPDATE, DELETE
--AS
--BEGIN
--UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE());
--END;

--SELECT [CPF], [NOME], [IDADE], [DATA_NASCIMENTO], 
--    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) AS IDADE_ATUAL
--FROM CLIENTES

--UPDATE CLIENTES SET VOLUME_COMPRA = 25000 WHERE CPF = '1471156710'

--SELECT [CPF], [NOME], [IDADE], [DATA_NASCIMENTO], 
--    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) AS IDADE_ATUAL
--FROM CLIENTES
--------------
--CREATE TABLE TAB_CHECK
--(
--	ID INT NOT NULL,
--	NOME VARCHAR (50) NULL,
--	IDADE INT NULL,
--	CIDADE VARCHAR(50) NULL,
--	CONSTRAINT CHK_IDADE CHECK (IDADE >= 18)
--);

--INSERT INTO TAB_CHECK VALUES (1,'JOÃO',19,'RIO DE JANEIRO');
--INSERT INTO TAB_CHECK VALUES (1,'PEDRO',16,'RIO DE JANEIRO');
--INSERT INTO TAB_CHECK VALUES (1,'PEDRO',20,'RIO DE JANEIRO');

--CREATE TABLE TAB_CHECK2
--(
--	ID INT NOT NULL,
--	NOME VARCHAR (50) NULL,
--	IDADE INT NULL,
--	CIDADE VARCHAR(50) NULL,
--	CONSTRAINT CHK_IDADE2 CHECK (
--									(IDADE >= 18 AND CIDADE = 'RIO DE JANEIRO')
--									OR
--									(IDADE >= 16 AND CIDADE = 'SÃO PAULO')
--								)
--);

--INSERT INTO TAB_CHECK2 VALUES (1,'JOÃO',19,'RIO DE JANEIRO');
--INSERT INTO TAB_CHECK2 VALUES (2,'PEDRO',17,'SÃO PAULO');

--SELECT * FROM TAB_CHECK2
